export const PIGMENT_MAP = [
  { h: [0, 12], s: [20, 100], l: [15, 35], pigment: "Burnt Umber", friendly: "Chocolate" },
  { h: [0, 12], s: [20, 100], l: [35, 55], pigment: "Venetian Red", friendly: "Brick" },
  { h: [0, 12], s: [50, 100], l: [55, 80], pigment: "Cadmium Red Light", friendly: "Tomato" },
  { h: [0, 12], s: [20, 50], l: [55, 80], pigment: "English Red", friendly: "Dusty Rose" },
  { h: [12, 30], s: [30, 100], l: [20, 45], pigment: "Burnt Sienna", friendly: "Rust" },
  { h: [12, 30], s: [30, 100], l: [45, 70], pigment: "Cadmium Orange", friendly: "Tangerine" },
  { h: [12, 30], s: [10, 30], l: [30, 60], pigment: "Raw Umber", friendly: "Coffee" },
  { h: [30, 50], s: [30, 100], l: [40, 70], pigment: "Yellow Ochre", friendly: "Honey" },
  { h: [30, 50], s: [30, 100], l: [70, 90], pigment: "Naples Yellow", friendly: "Buttercream" },
  { h: [50, 65], s: [40, 100], l: [45, 75], pigment: "Cadmium Yellow", friendly: "Sunflower" },
  { h: [50, 65], s: [40, 100], l: [75, 95], pigment: "Lemon Yellow", friendly: "Sunshine" },
  { h: [65, 90], s: [20, 60], l: [30, 55], pigment: "Olive Green", friendly: "Moss" },
  { h: [65, 90], s: [60, 100], l: [40, 70], pigment: "Yellow Green", friendly: "Lime" },
  { h: [90, 150], s: [20, 60], l: [20, 45], pigment: "Hooker's Green", friendly: "Forest" },
  { h: [90, 150], s: [30, 100], l: [35, 60], pigment: "Sap Green", friendly: "Leaf" },
  { h: [90, 150], s: [30, 100], l: [60, 80], pigment: "Permanent Green Light", friendly: "Mint" },
  { h: [150, 185], s: [30, 100], l: [25, 50], pigment: "Viridian", friendly: "Deep Teal" },
  { h: [150, 185], s: [30, 100], l: [50, 75], pigment: "Cobalt Teal", friendly: "Aqua" },
  { h: [185, 210], s: [30, 100], l: [25, 45], pigment: "Prussian Blue", friendly: "Deep Ocean" },
  { h: [185, 210], s: [30, 100], l: [45, 70], pigment: "Cerulean Blue", friendly: "Sky Blue" },
  { h: [185, 210], s: [10, 30], l: [50, 75], pigment: "Payne's Grey Blue", friendly: "Rainy Day" },
  { h: [210, 240], s: [30, 100], l: [15, 35], pigment: "Indigo", friendly: "Midnight" },
  { h: [210, 240], s: [30, 100], l: [35, 55], pigment: "Ultramarine Blue", friendly: "Deep Blue" },
  { h: [210, 240], s: [30, 100], l: [55, 75], pigment: "Cobalt Blue", friendly: "Cornflower" },
  { h: [240, 270], s: [20, 100], l: [20, 45], pigment: "Dioxazine Violet", friendly: "Plum" },
  { h: [240, 270], s: [20, 100], l: [45, 70], pigment: "Ultramarine Violet", friendly: "Lavender" },
  { h: [270, 310], s: [20, 100], l: [20, 45], pigment: "Quinacridone Violet", friendly: "Grape" },
  { h: [270, 310], s: [20, 100], l: [45, 70], pigment: "Permanent Magenta", friendly: "Orchid" },
  { h: [270, 310], s: [20, 100], l: [70, 90], pigment: "Opera Rose", friendly: "Bubblegum" },
  { h: [310, 345], s: [20, 100], l: [25, 50], pigment: "Alizarin Crimson", friendly: "Wine" },
  { h: [310, 345], s: [30, 100], l: [50, 75], pigment: "Quinacridone Rose", friendly: "Hot Pink" },
  { h: [345, 360], s: [50, 100], l: [30, 55], pigment: "Cadmium Red", friendly: "Fire Engine" },
  { h: [345, 360], s: [50, 100], l: [55, 80], pigment: "Scarlet Lake", friendly: "Cherry" },
];

export const WATERCOLOR_PIGMENTS = [
  // Reds
  { hex: "#C44536", name: "Cadmium Red", friendly: "Fire Engine", group: "Reds" },
  { hex: "#A23028", name: "Alizarin Crimson", friendly: "Wine", group: "Reds" },
  { hex: "#D65B5B", name: "Scarlet Lake", friendly: "Cherry", group: "Reds" },
  { hex: "#C94D6E", name: "Quinacridone Rose", friendly: "Hot Pink", group: "Reds" },
  { hex: "#E87A90", name: "Opera Rose", friendly: "Bubblegum", group: "Reds" },
  // Oranges & Earth
  { hex: "#C9713D", name: "Burnt Sienna", friendly: "Rust", group: "Oranges & Earth" },
  { hex: "#D4903A", name: "Cadmium Orange", friendly: "Tangerine", group: "Oranges & Earth" },
  { hex: "#6B4E3D", name: "Raw Umber", friendly: "Coffee", group: "Oranges & Earth" },
  { hex: "#5C3D2E", name: "Burnt Umber", friendly: "Chocolate", group: "Oranges & Earth" },
  { hex: "#A0522D", name: "Venetian Red", friendly: "Brick", group: "Oranges & Earth" },
  // Yellows
  { hex: "#D4A843", name: "Yellow Ochre", friendly: "Honey", group: "Yellows" },
  { hex: "#E8C84A", name: "Cadmium Yellow", friendly: "Sunflower", group: "Yellows" },
  { hex: "#F0DC6E", name: "Lemon Yellow", friendly: "Sunshine", group: "Yellows" },
  { hex: "#E8C98A", name: "Naples Yellow", friendly: "Buttercream", group: "Yellows" },
  { hex: "#C4A235", name: "Raw Sienna", friendly: "Amber", group: "Yellows" },
  // Greens
  { hex: "#5B8C3E", name: "Sap Green", friendly: "Leaf", group: "Greens" },
  { hex: "#3A6B35", name: "Hooker's Green", friendly: "Forest", group: "Greens" },
  { hex: "#6B7F3A", name: "Olive Green", friendly: "Moss", group: "Greens" },
  { hex: "#78B060", name: "Permanent Green", friendly: "Mint", group: "Greens" },
  { hex: "#2E8B7A", name: "Viridian", friendly: "Deep Teal", group: "Greens" },
  // Blues
  { hex: "#4A7C91", name: "Cerulean Blue", friendly: "Sky Blue", group: "Blues" },
  { hex: "#3D5A80", name: "Indigo", friendly: "Midnight", group: "Blues" },
  { hex: "#2C4A6E", name: "Prussian Blue", friendly: "Deep Ocean", group: "Blues" },
  { hex: "#3F69AA", name: "Ultramarine Blue", friendly: "Deep Blue", group: "Blues" },
  { hex: "#5A8BBF", name: "Cobalt Blue", friendly: "Cornflower", group: "Blues" },
  { hex: "#4BA8B5", name: "Cobalt Teal", friendly: "Aqua", group: "Blues" },
  // Violets
  { hex: "#8B4E6A", name: "Quinacridone Violet", friendly: "Grape", group: "Violets" },
  { hex: "#5C3D6E", name: "Dioxazine Violet", friendly: "Plum", group: "Violets" },
  { hex: "#7A5DAA", name: "Ultramarine Violet", friendly: "Lavender", group: "Violets" },
  { hex: "#9E5B8A", name: "Permanent Magenta", friendly: "Orchid", group: "Violets" },
  // Neutrals
  { hex: "#4A4A4A", name: "Payne's Grey", friendly: "Storm Cloud", group: "Neutrals" },
  { hex: "#6E6B64", name: "Davy's Grey", friendly: "Pebble", group: "Neutrals" },
  { hex: "#2A2A2A", name: "Ivory Black", friendly: "Charcoal", group: "Neutrals" },
];

export const COLOR_GROUPS = ["Reds", "Oranges & Earth", "Yellows", "Greens", "Blues", "Violets", "Neutrals"];
